title: Articles
description: Blog by Alaukik N. Pant
author: Alaukik Pant
github: https://github.com/alaukiknpant
disqus_shortname: alaukiknpant
# google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
   # - icon: fa-facebook
   #  link: "#"
   # - icon: fa-twitter
   #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/alaukik-p-096824108/"
  #  - icon: fa-stack-exchange
  #    link: "#"
    - icon: fa-github
      link: "https://github.com/alaukiknpant"



urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/


url: "https://alaukiknpant.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
